package net.myerichsen.fonkod;

/**
 * @author Michael Erichsen
 * 
 * This class can test Fonkod
 * 
 */
public class Tester {

	/**
	 * Can be used for testing
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		// I gedcom-programmet skal hvert person- og stednavn have doublephone
		// og denne som alternative navne, så der kan søges på alle tre.
		String[] inputNavne = { 
				"Aabye", "Aagaard", "Aagesen", "Aalborig",
				"Aanonsdatter", "Aase", "Aaskov", "Aaslund", "Aasted",
				"Abbestee", "Abel", "Åberg", "Abildgaard", "Abraham",
				"Abrahamsen", "Abramczuk", "Acthon", "Acthonia", 
				"af Putbus",
				"Agensø", "Agergaard", "Agier", "Agricola", "Ahlefeldt",
				"Ahlefeldt-Laurvig", "Akeleye", "Alberti", "Albertsen",
				"Albrechtsen", "Albretsen", "Alexander", "Allerup",
				"Allgulander", "Alliot", "Almisdatter", "Alten", "Althausen",
				"Alværn", "Alvarez", "Ambjørn", "Ambrosia", "Ammentorp",
				"Amos", "Amundsen", "Ancher", "Anchersdatter", "Andersdatter",
				"Andersdotter", "Andersen", "Andersen-Kjær", "Anderson",
				"Andersson", "Andreasen", "Andreassen", "Andresdatter",
				"Andresen", "Andrews", "Andrup", "Angelo", "Anglov",
				"Anker-Møller", "Anskarsen", "Anthonsen", "Antonisen",
				"Antonsson", "Aquivallinus", "Arctander", "Aredsen",
				"Arentzen", "Arenvall", "Arff", "Arffmann", "Arfmann", "Arias",
				"Aristsen", "Armoese", "Arnesdatter", "Arnesen",
				"Arnesen-Kall", "Arnkiel", "Arnolds", "Arpe", "Arrildt",
				"Arvesdatter", "Arvesen", "Arvidsen", "Arving", "Ascanius",
				"Aslaksen", "Asmussen", "Assarsdatter", "Assing", "Atkin",
				"Ator", "Aubertin", "Augsburg", "August", "Axelsdatter",
				"Ayre", "Baad", "Baare", "Bach", "Bache", "Bachele", "Back",
				"Bæk", "Bærildsdatter", "Bærildsen", "Bafenerda", "Bager",
				"Bagge", "Bagger", "Baggesdatter", "Baggesen", "Bagley",
				"Bahrenscheer", "Baillot", "Bak", "Baker", "Bakken", "Baldwin",
				"Ball", "Balle", "Balsborg", "Balslay", "Baltzar",
				"Baltzersdatter", "Baltzersen", "Bang", "Bank-Rasmussen",
				"Baranski", "Barchalia", "Baret", "Barfred",
				"Baronesse Reedtz-Thott", "Barr", "Barry", "Barth",
				"Bartholdy", "Bartholin", "Bartholin-Eichel",
				"Bartholomæusdatter", "Bartskær", "Bartskærer", "Basballe",
				"Basse", "Bassøe", "Batemen", "Baudissin", "Bauer-Johansen",
				"Baurath", "Bautz", "Baxter", "Bay", "Bayer", "Beal", "Beam",
				"Bean", "Beaver", "Bech", "Bech-Bruun", "Bechmann", "Beck",
				"Becker", "Beckmann", "Beder", "Bedsted Madsdatter", "Beege",
				"Begtrup", "Behrens", "Bek", "Bekker", "Bell", "Bellins",
				"Bendtsdatter", "Bendtsen", "Bendz", "Bengtsson", "Bennedsen",
				"Bennichmann", "Bense", "Benstead", "Bentley", "Bentsen",
				"Bentzen", "Bercholten", "Berg", "Bergin", "Bergman",
				"Bergmann", "Bergström", "Bergstrøm", "Berlin", "Bernadotte",
				"Bernard", "Berner", "Bertelsdatter", "Bertelsen",
				"Berthelsdatter", "Berthelsen", "Bertrand", "Betti",
				"Beuschel", "Beyer", "Bezzoli", "Bidstrup", "Biering",
				"Biering-Sørensen", "Bigum", "Bild", "Billing", "Bing",
				"Birch", "Birkedal", "Bischoff", "Bisson", "Bjerre",
				"Bjerregaard", "Björkenberg", "Björklund", "Bjørnsdatter",
				"Bjørnsen", "Black", "Blad", "Blæsbjerg-Christiansen",
				"Blåfod", "Blakeney", "Blanvallet", "Blasholtz", "Blatan",
				"Blatter", "Blem", "Blicher", "Blichert", "Blichert-Hansen",
				"Blichfeldt", "Blix", "Bloch", "Blom", "Blumensaat", "Blykop",
				"Blytmann", "Bock", "Bockenhoffer", "Bodenhoff", "Bøeg",
				"Boemand", "Boëtius", "Bøge", "Bøggild", "Bøgh", "Bøgild",
				"Bogle", "Bøgvad", "Bohem", "Böhme", "Bøhme", "Bohn",
				"Boiesen", "Boisen", "Boje", "Bojesen", "Bolinder", "Boll",
				"Bollers", "Bollesdatter", "Bollesen", "Bolt", "Bolvig",
				"Bonde", "Bondesen", "Bonnevie", "Bonnevie-Dyssegård",
				"Bonnevie-Nielsen", "BonnevieOlesen", "Bookall", "Borch",
				"Borchhorst", "Borg", "Borges", "Børgesen", "Börjesson",
				"Bornemann", "Borntzen", "Borreby", "Borregaard", "Borring",
				"Borringholm", "Botkin", "Bourgoin", "Bourke", "Bøving",
				"Bowden", "Boxsell", "Boye", "Bøye", "Boysen", "Brackmann",
				"Bradbury", "Brændgaard", "Bræstrup", "Bramdroph", "Brams",
				"Brandenborg", "Brandi", "Brandt", "Brasce", "Brasch",
				"Bredahl", "Bredenberg", "Bredmose", "Bredsdorff", "Bremer",
				"Brennan", "Brenteson", "Brethvad", "Breum", "Brew", "Breyen",
				"Bride", "Brinch", "Broch", "Brock", "Brockhoff", "Broder",
				"Brodersen", "Brogaard", "Brøgger", "Bromfield",
				"Bromfield-Geld", "Brommer", "Brøndum", "Brøns", "Brorsen",
				"Brøseth", "Brotherwood", "Broughton", "Brown", "Brüel",
				"Bruhn", "Brun", "Brunin", "Brunn", "Brusch", "Brusendorff",
				"Bruun", "Bruun-Andersen", "Bryant", "Bryde", "Brygger",
				"Bryld", "Bub", "Buch", "Buck", "Budd", "Budde", "Bugge",
				"Buitenhuis", "Bull", "Bullock", "Bülow", "Bundt", "Bunkeflod",
				"Burke", "Burns", "Busato", "Busch", "Busche", "Busck",
				"Busenbark", "Bussmann", "Butler", "Buttars", "Büttener",
				"Buttenschøn", "Buus", "Bydelsbach", "Bydelsbak", "Byers",
				"Byington", "Bylsma", "Byrresen Nielsen", "Calkins",
				"Callesen", "Callow", "Cameron", "Campbell", "Cantzler",
				"Cargill", "Carlisle", "Carlsdotter", "Carlsen", "Carøe",
				"Carstensen", "Caruso", "Casey", "Caspersdatter",
				"Castensdatter", "Castensen", "Cederfeld de Simonsen",
				"Challoner", "Chamberlain", "Charbonnel", "Chimes", "Choudaba",
				"Christensdatter", "Christensen", "Christensen",
				"Christensen-Palmer", "Christiani", "Christiansdatter",
				"Christiansen", "Christoffersen", "Christophersdatter",
				"Christophersen", "Claudi", "Clausdatter", "Clausen",
				"Clayton", "Clemens", "Clemensdatter", "Clemensen",
				"Clemmensdatter", "Clemmensen", "Cline", "Clod", "Cobb",
				"Colding", "Cole", "Coleman", "Collins", "Colman",
				"comtesse Moltke", "Conlon", "Connor", "Conradsen", "Cooley",
				"Cooper", "Cor", "Cordes", "Corn", "Corneliussen", "Coudray",
				"Courtault", "Coutu", "Couvreur", "Cowley", "Coyle", "Crain",
				"Cramer", "Crane", "Crone", "Cronfelt", "Crowford", "Crowley",
				"Curtis", "Curtiss", "Curtz", "Cusack", "Dahl", "Dahlbom",
				"Dal", "Dalberg", "Dalsgaard", "Dam", "Damgaard", "Damm",
				"Damsgaard", "Dan", "Danborg", "Danchell", "Danco",
				"Danco-Heil", "Danebod", "Danholm", "Danholt", "Dania",
				"Danielsdatter", "Danielsen", "Davidsdatter", "Davidsen",
				"Davis", "Day", "de Benidetti", 
				"Debes", "de Carlo",
				"de Cernin", "de Cernyn", "Deering", "de Fontenay", "Dehle",
				"de la Cour", "De Lai", "Demant", "Demén", "Demén-Villaume",
				"de Neergaard", "den Gamle", "Denyer", "de Ottenbüttel",
				"de Regt", "de Rehling-Qvistgaard", "de Renouard", "Deschamps",
				"Desin", "Desmond", "Destiana", "de Svanenskjold",
				"de Svanenskjold Hoff", "Dethlefsen", "Deubel", "Devecchi",
				"de Villers Grand Champ", "Dewar", "de Watteville", "Dhaynaut",
				"Dich", "Diderichsen", "Diech", "Dierks", "Dige", "Dinesen",
				"Dirch", "Dirchsen", "Ditlevsen", "Ditzel", "Dixen",
				"Dollerup", "Dolman", "Dølner", "Domgaard", "Domino", "Donald",
				"Donoghue", "Dooley", "Doran", "Dorn", "Dowdell", "Dowdle",
				"Down", "Doyle", "Drabsch", "Dragsted", "Drechsel", "Dreier",
				"Dreilov", "Dreiøe", "Drejer", "Dresing", "Drewsen", "Dreyer",
				"Drovin", "Du Coudray", "Ducoudray", "Ducoudray-Holstein",
				"Due", "Duelund", "Due-Petersen", "duPlan", "Dupont", "Dupuis",
				"Dybbroe", "Dyhrberg", "Dyre", "Dyring", "Dyrkov",
				"Dyssegaard", "Dyssel", "Ebbesdatter", "Ebbesen", "Eberhardt",
				"Ebert", "Echsteen", "Edholm", "Edinger", "Edwards", "Ege",
				"Egede", "Egholm", "Ehrenreich", "Ehrhardt", "Eilersen",
				"Eilert", "EilertPedersen", "Eisensøe", "Ejlertsen", "Eklund",
				"Ekman", "Ekstrand", "Elbæk", "Elberling", "Eliasen",
				"Eliassen", "Ellefsson", "Ellekvist", "Ellenberger", "Eller",
				"Ellertsen", "Elm", "Elster", "Emery", "Endorph", "Enevoldsen",
				"Engberg", "Engels", "Engelsted", "Engelund", "Enger",
				"Enghoff", "Englev", "Engquist", "Engsig", "Engsig-Karup",
				"Erichsdatter", "Erichsen", "Erickson", "Eriksdatter",
				"Eriksen", "Eriksson", "Erinder", "Erlandsen", "Ernfors",
				"Ernst", "Ernstsdatter", "Esbernsdatter", "Esbersdatter",
				"Esbersen", "Eschildsen", "Eskesen", "Esmann", "Espersdatter",
				"Espersen", "Espesen", "Esrum", "Essendrop", "Essendrup",
				"Esser", "Estridsen", "Everstein", "Ewald", "Faartoft",
				"Faber", "Fabiansen", "Fabricius", "Fæster", "Fafeita",
				"Fage-Pedersen", "Fagerlund", "Fägerstrand", "Fahlenkamp",
				"Fahlgreen", "Falk", "Falkenberg", "Falkner", "Fallesen",
				"Falster", "Farr", "Fast", "Fauerby", "Faurbo", "Faxner",
				"Fehn", "Feilberg", "Feiring", "Feldberg", "Feldhütter",
				"Felton", "Felumb", "Fenger", "Fernqvist", "Fibiger", "Fich",
				"Fiedler", "Fiil", "Filipsdotter", "Filskov", "Finch",
				"Fink-Jensen", "Finnerup", "Fischer", "Fish", "Fisker",
				"Fitzgerald", "Fleischer", "Flensborg", "Fleron",
				"Flinck-Rosenkranz", "Flintrup", "Floor", "Flor", "Fluton",
				"Fobian", "Foerseu", "Foersom", "Fog", "Fogh", "Fogh-Andersen",
				"Fontaine", "Forsee", "Forsyth", "Fort", "Foss", "Fox",
				"Frambo", "Françon", "Frandsen", "Frank", "Frantsdatter",
				"Franz", "Frappi", "Frear", "Frederichsdatter", "Frederichsen",
				"Frederiksdatter", "Frederiksen", "Freding-Poulsen", "Freese",
				"Frende", "Friborg", "Frick", "Fricke", "Frid", "Friderichsen",
				"Fridrichsdatter", "Fridsch", "Friedstedt", "Friend", "Fries",
				"Friis", "Friisberg", "Friis-Mikkelsen", "Frisenborg",
				"Frisenette", "Frisk", "Froberg", "Fröberg", "Frobøse",
				"Frost", "Fry", "Frydenlund", "Fuchs", "Fugl", "Fuglede",
				"Fuglsang", "Fullmer", "Funch", "Funder", "Fyhn", "Gaardmand",
				"Gad", "Gadd", "Gade", "Gädeken", "Gagge", "GaggeGagge",
				"Gagghe", "Galen", "Gallois", "Galster", "Galthen",
				"Gammelgaard", "Gamshard", "Gamst", "Garcia", "Garde",
				"Garrald", "Gebert", "Gedde", "Gede", "Geelmuyden", "Geertsen",
				"Geld", "Geldart", "Gellespie", "Gemmell", "Gerlach",
				"Gernyx-Hansen", "Gerstenberg", "Ghede", "Giede", "Gierløv",
				"Giertssøn", "Gilbe", "Gimmini", "Giødich", "Givern",
				"Gjellerup", "Gjerløv", "Gjerløw", "Gjertsen", "Gjødvad",
				"Gjordsdatter", "Gjørup", "Glæsner", "Glahn", "Glatz",
				"Gliemann", "Glud", "Godfredsdatter", "Godske-Nielsen",
				"Godtfredsen", "Goldin", "Goldschmidt", "Gorm-Knudsen",
				"Gornitzka", "Gotfredsen", "Göthe", "Gottfredsen", "Gottlieb",
				"Gottschau", "Gøtzsche", "Graa", "Graae", "Grabow", "Grady",
				"Graff", "Graff-Nielsen", "Grage", "Grahann", "Gram",
				"Grandlev", "Grauer", "Graulev", "Gravensteen", "Gravenstein",
				"Graversen", "Gravete", "Green", "Gregersdatter", "Gregersen",
				"Greiff", "Greisen", "Grelsby", "Greve", "greveMoltke",
				"Gripka", "Groftved", "Gronemann", "Grønhaug", "Grønlund",
				"Grønvold", "Grosen", "Grosskopff", "Grosskopff-Berner",
				"Grøtcher", "Grøtner", "Grove", "Grubbe", "Grum-Schwensen",
				"Grundy", "Grüner", "Guay", "Gudbjerg", "Gudme", "Gudmundsen",
				"Gudmundsson", "Guerrier", "Gug", "Guldager", "Guldberg",
				"GuldbergHaig", "Guldborg", "Guldmann", "Gulløv", "Gulmann",
				"Gumløs", "Gundersen", "Gundestrup", "Gundorph", "Gunnarssen",
				"Gunner", "Gunthel", "Gustafson", "Gustafsson", "Gyldenkerne",
				"Gyldenstierne", "Gyldenstjerne", "Haagen", "Haagensdatter",
				"Haagensen", "Haagh", "Haastrup", "Hack", "Haderup",
				"Hadsteen", "Hækkerup", "Hage", "Hagefeldt", "Hagemeister",
				"Hagen", "Hagens", "Hakonsen", "Halanzy", "Halberg", "Hald",
				"Hall", "Hallbäck", "Hallbom", "Hals", "Hamann", "Hammerich",
				"Hammerlund", "Hammerstad", "Hammond", "Hanbury", "Handest",
				"Handewitt", "Hansdatter", "Hansen", "Hanson", "Hanssen",
				"Hansson", "HaraldsenLitle", "Harboe", "Harder", "Hardt",
				"Hare", "Harmison", "Harpøth", "Harrington", "Harris",
				"Hartkings", "Hartoft", "Harttung", "Hartvig", "Hartvigsen",
				"Hartwig", "Hass", "Hasse", "Hasselbalch", "Hastrup", "Hauge",
				"Haugland", "Hauka", "Haung", "Hauptmann", "Hay", "Hayward",
				"Hecquet", "Hedberg", "Hede", "Hedebo", "Hedegaard", "Hedeman",
				"Heegaard", "Heegaard-Jensen", "Heiberg", "Heide", "Heiede",
				"Heigaard", "Heil", "Heilesen", "Hein", "Heinesen",
				"Helgesson", "Hellesen", "Helligsdatter", "Hellmund",
				"Hellner", "Hellner-Nielsen", "Helm-Petersen", "Helms",
				"Hemmingsen", "Henault", "Henckel", "Hendrichsdatter",
				"Hendrichsen", "Hendricksen", "Hendriksen", "Heniochus",
				"Henius", "HenningAlbertsdatter", "Hennings", "Henningsdatter",
				"Henningsen", "Henrichsdatter", "Henrichsen", "Henricsson",
				"Henriksdatter", "Henriksen", "Henriques", "Henth", "Herbst",
				"Herfort", "Herfurth", "Herlev", "Herlichsen", "Herlogsdatter",
				"Hermansen", "Herschend", "Herskind", "Hertz", "Heseler",
				"Hess", "Hessner", "Heurlin", "Hewitt", "Heyn", "Heyne",
				"Heyner", "Hildebrandt", "Hildestrøm", "Hill", "Hillersborg",
				"Hillerslev", "Hincheldey", "Hinge", "Hipps", "Hjordt",
				"Hjørringgaard", "Hjorth", "Hjortholm", "Hochbrandt", "Høeg",
				"Høegh-Guldberg", "Hoff", "Høffding", "Hoffmann", "Hoffmeyer",
				"Høg", "Høgh", "Høglund", "Høhne", "Høholt", "Højelse",
				"Højland", "Holch", "Holgersen", "Holladay", "Holland", "Holm",
				"Holmer", "Holmes", "Holmgersen", "HolmgerssonLånge",
				"Holmgren", "Holst", "Holstboe", "Holstein", "Holt", "Holten",
				"Holtorp", "Holvert", "Hommelgaard", "Hoormann", "Hopkins",
				"Hopp", "Hoptrup", "Hørdum", "Hørlück", "Horn", "Horndal",
				"Hornskov", "Hornum", "Hornwain", "Horst", "Horton", "Hørved",
				"Høsche", "Høst", "Høstmark", "HostrupSchultz",
				"Hostrup-Schultz", "Hotvedt", "Hougaard", "Hovland", "Hovmand",
				"Howden-Rønnenkamp", "Høyer", "Høygaard-Nielsen", "Høyrup",
				"Hozian", "Hubbard", "Hude", "Hudson", "Hunter", "Hurup",
				"Hurwitz", "Husted", "Hvide", "Hviid", "Hvoslef", "Hyllested",
				"Hylsenberg", "Hynkemeier", "Ibsdatter", "Ibsen", "Ide",
				"Igglund", "Ignatiev", "Ilsøe", "Ingerslev", "Ingvordsen",
				"Ingvorsen", "Ipsdatter", "Ipsen", "Irgens-Møller",
				"Isaachsen", "Isachsen", "Isaksdatter", "Ishøy", "Itkis",
				"ITveskæg", "Iuul", "IVafGleichen", "Iversdatter", "Iversen",
				"Jacobsdatter", "Jacobsen", "Jacobsons", "Jakobsen", "James",
				"Jamil", "Jansen", "Janson", "Jansson", "Janting", "Jantz",
				"Jantzen", "Jantzen-Holst", "Jarvis", "Jasper", "Jellesmark",
				"Jennings", "Jensdatter", "Jensen", "Jensen-Holm",
				"JensenJonsdotter", "Jeppesdatter", "Jeppesen", "Jeppsson",
				"Jernskjæg", "Jespersen", "Jessen", "Jetlund", "Jochumsen",
				"Joensdatter", "Joensen", "Johannesdatter", "Johannesen",
				"Johannessen", "Johansdatter", "Johansen", "Johansson",
				"Johnsdatter", "Johnsen", "Johnson", "Johnsson", "Johnstone",
				"Joliffe", "Jonasdatter", "Jonasen", "Jones", "Jönsdotter",
				"Jonsen", "Jonsson", "Jönsson", "Jønsson", "Jonzén", "Jørgen",
				"Jørgensdatter", "Jorgensen", "Jørgensen", "Joyce", "Juel",
				"JueSue", "Juhl", "Jul", "Jürgensen", "Justus", "Juul",
				"Juul-Mortensen", "Jyde", "Kærgård", "Kalkar", "Kall",
				"Kall-Eberhardt", "Kallenbach", "Kall-Rasmussen", "Kames",
				"Kampmann", "Kappers", "Karlsen", "Karmark", "Kastrup",
				"Kavarno", "Kean", "Kegebein", "Keiding", "Kejlskov", "Kelet",
				"Kelly", "Kelou", "Kemp", "Kent", "Kenvad", "Kidmose",
				"Kieldsen", "Kielgast", "Kielland", "Kielstrup", "Kierboe",
				"Kierulfsdatter", "Kindler", "Kirby", "Kirch", "Kirchheiner",
				"Kirk", "Kirkeby", "Kirkegaard", "Kirkemann", "Kirkeskov",
				"Kirketerp", "KirstenMagnaRigmor", "Kjær", "Kjærbye",
				"Kjærgaard", "Kjærsgaard", "Kjærulf", "Kjeldsen", "Kjelgaard",
				"Kjelgaard-Kronborg", "Kjenner", "Kjøller", "Klausen", "Kleis",
				"Kliewer", "Klingberg", "Klinge", "Klitgaard", "Klo",
				"Klöcker", "Kloe", "Kloumann", "Klubien", "Klüver", "Kluw",
				"Klyver", "Knakkergaard", "Kneus", "Kneyln", "Knoblauch",
				"Knud", "Knudsdatter", "Knudsen", "Knuppert", "Koch", "Kock",
				"Kodriaty", "Koefod", "Koefoed", "Kofoed", "Kofoed-Olsen",
				"Kofoed-Thorsager", "Kokborg", "Köller", "Kolling", "Kønicke",
				"Konig", "Kønig", "Korch", "Korff", "Korgaard", "Kornerup",
				"Korsbech", "Korsgaard", "Kørsing", "Korsø", "Kortegaard",
				"Køster", "Kraft", "Krag", "Kragelund", "Kragh", "Krahe",
				"Krarup", "Krasilnikoff", "Kraul", "Krause", "Krauthoff",
				"Kreibe", "Kreimer", "Kretzschmer", "Krieger", "Kringelbach",
				"Kristensdatter", "Kristensen", "Kristiansen", "Kristoffersen",
				"Krjukova", "Krog", "Krøger", "Krogh", "Kromer", "Krøyer",
				"Krüger", "Krumhausen", "Krummedige", "Krummendiek", "Kruse",
				"Krutmeier", "Kruuse", "Kryger", "Kvist", "Kvistgaard", "Kyhl",
				"Laage", "laCour", "Lagesdatter", "Lambert", "Landry", "Lang",
				"Langballe", "Lange", "Langeland", "Langemach", "Langendorff",
				"Langgaard", "Langhorn", "Langkilde", "Lanier", "Larkins",
				"Larsdatter", "Larsdotter", "Larsen", "Larson", "Larssen",
				"Larsson", "Lassen", "Lasseson", "Lasson", "Lauesdatter",
				"Laugesen", "Laumann", "Launy", "Laurberg", "Laurensdatter",
				"Laurentsdatter", "Lauridsdatter", "Lauridsen", "Lauridssen",
				"Lauritsdatter", "Lauritsen", "Lauritzen", "Laursdatter",
				"Laursen", "Lausen", "Lavesdatter", "Law", "laWalle",
				"Lawkowicz", "Leasure", "leClerc", "Lee", "Leegaard", "Leeser",
				"Legge", "Lehrmann", "Leifer", "Lellinge", "Lembke",
				"Lembourn", "Lemcke", "Lemos", "Lendi", "Lennartz",
				"Lennertzdatter", "Leo", "Leonard", "lePoull", "leRoy",
				"Lesler", "Lesse", "Lester", "Lethmathe", "Lett", "Leuning",
				"Lewardia", "Lewis", "Liebenberg", "Liechty", "Lihme",
				"Liljehult", "Lille", "Lillelund", "Lillienskjold", "Limschou",
				"Lind", "Lindahl", "Lindbæk", "Lindberg", "Linde",
				"Lindekilde", "Lindemann", "Lindenblad", "Lindenfeld",
				"Lindgren", "Lindhard", "Lindhardt", "Lindschou", "Linstow",
				"Lister", "Litle", "Livier", "Ljufström", "Lobedanz", "Locher",
				"Løhr", "Lohse", "Lomborg", "Lomholt", "Lønberg", "Longsdale",
				"Lordan", "Lorentsen", "Lorentzen", "Lorenzen", "Lose",
				"Losen", "Løssl", "Løth-Jensen", "Lottrup", "Lovie", "Löwe",
				"Løwe", "Löwenstein", "Løye", "Lübecker", "Luciatte",
				"Ludewig", "Ludvigsen", "Luffe", "Lund", "Lundberg", "Lunde",
				"Lundgren", "Lundin", "Lundquist", "Lundqvist",
				"Lund-Sørensen", "Lunge", "Lunn", "Lütken", "Lüxdorph",
				"Lydichsen", "Lykke", "Lynderup", "Lyng", "Lynge", "Lyngse",
				"Lyngsø", "Lyngvåg", "Lynøe", "Lystager", "Lytle", "Maahr",
				"Maccabæus", "MacDonald", "Macholt", "Madié", "Madsdatter",
				"Madsen", "Madtzdatter", "Magaard", "Maher", "Majoner",
				"Major", "Malchow-Møller", "Malin", "Malinowska", "Malmgreen",
				"Malmø", "Malmquist", "Mangor", "Manthey", "Manwell",
				"Marchall", "Marcher", "Marchmann", "Marcker", "Marckmann",
				"Marco", "Marcusdatter", "Marcussen", "Marek", "Marke",
				"Markmand", "Marks", "Markussen", "Marling", "Marre", "Marsh",
				"Martell", "Martin", "Martinusdatter", "Marx", "Mason",
				"Mathiasdatter", "Mathiasen", "Mathiassen", "Mathiesen",
				"Mathisen", "Matos", "Mattson", "Mauritzdatter", "Mauritzen",
				"Mayer", "MazardelaGarde", "McCarthy", "McClellan",
				"McCormack", "McDonald", "McDonell", "McFadyen", "McGee",
				"McGovern", "McGuire", "McKay", "McKinney", "McLaughlin",
				"McLean", "McNevin", "Meacham", "Mechernsen", "Megyessi",
				"Mehl", "Meiger", "Meincke", "Meinertz", "Meisler", "Melchior",
				"Mellerup", "Mengs", "Mercker", "Merkel", "Metzroth",
				"Meulengracht", "Meyer", "Michael", "Michel", "Michelbecker",
				"Michell", "Michelsdatter", "Michelsen", "Michielin",
				"Mickelsdatter", "Mikkelborg", "Mikkelsdatter", "Mikkelsen",
				"Mikkelson", "Miller", "Mills", "Misurraca", "Mitchinson",
				"Modig", "Mogensdatter", "Mogensen", "Møinichen", 
				"Mokrzyczki",
				"Moller", "Møller", "Møller-Holmstoel", "Møller-Holst",
				"Mollerup", "Moltke", "Moltke-Hoff", "Monrad", "Monrath",
				"Monsdatter", "Monsen", "Monson", "Mønsted", "Mønster",
				"Morawski", "Mørch", "Mørck", "Morgan", "Morgareidge",
				"Morgenstjærne", "Moritz", "Mørk", "Mormay", "Moron", "Mors",
				"Mortensdatter", "Mortensen", "Morton", "Mosberg", "Mose",
				"Moss", "Motmans", "Mouritsen", "Mouritzen", "Moyston",
				"Mühlensteth", "Müller", "Mumme", "Munch", "Munch-Petersen",
				"Munk", "Munksgaard", "Münster", "Murtagh", "Mwakitalu",
				"Myers", "Myhre", "Mylius-Erichsen", "Myre", "Nadolska",
				"Næsted", "Nagel", "Nathan", "Nathansen", "Nathanson",
				"Nattestad", "Nedergaard", "Neergaard", "Nees", "Nellemann",
				"Nellerød", "Nepen-Hutchison", "Nersting", "Nichols",
				"Nicholson", "Niel", "Nielsdatter", "Nielsen", "Nielsen",
				"NielsenLund", "NielsenToft", "NielsenWinther", "Nielson",
				"Niemans", "Nigels", "Nigelsen", "Nikolaisen",
				"Nikolajsdatter", "Nikulajevska", "Nilsdotter", "Nilsson",
				"Nipgaard", "Nisdatter", "Nissen", "Nistad", "Nitsche",
				"Noichol", "Nøies", "Nøjgaard", "Nørbye", "Nordberg",
				"Nordentoft", "NordentoftFisker", "Nordentoft-Jacobsen",
				"NordentoftThomsen", "Nordholt", "Nordlind", "Nørgaard",
				"Normann", "Nørregaard", "Nørrekjær", "Norrie", "Norsman",
				"Norstrøm", "Novak", "Nyborg", "Nygaard", "Nyholm", "Nyhuus",
				"Oates", "Obel", "Ochsner", "O\'Conell", "Ødbergsen",
				"Odegaard", "Odin", "Øelund", "O\'Flanigan", "O\'Flannigan",
				"Ohlsen", "Okubo", "Øland", "Oldesloe", "Olesdatter", "Olesen",
				"Olesson", "Olrik", "Olsdatter", "Olsdotter", "Olsen",
				"Olsen Nielsen", "Olson", "Olufsdatter", "Olufsen", "Ørgaard",
				"Ørkilde", "O\'Rourke", "Ørsted", "Ørum", "Øster",
				"Østergaard", "Østergren", "Österlund", "Österman", "Østrup",
				"Ott", "Otto", "Ottosen", "Ottow", "Ovaqqaorahou", "Overbeck",
				"Overgaard", "Ovesdatter", "Oxholm", "Paddleford", "Pæling",
				"Pallesdatter", "Pallesen", "Palliser", "Pallisgaard",
				"Palmer", "Palsby", "Paludan", "Paludanus", "Pan", "Panduro",
				"Panton", "Papck", "Papeke", "Paquot", "Parcell", "Paris",
				"Parré", "Parvari", "Passow", "Paulli", "Paulsen", "Paust",
				"Peake", "Pearson", "Peattie", "Pedersdatter", "Pedersdotter",
				"Pedersen", "Pegler", "Pennington", "Perbøl", "Perrochet",
				"Persen", "Persson", "Peschard", "Peschardt", "Petersen",
				"Petersen-Bæk", "Peterson", "Petræus", "Petrasi", "Pettersen",
				"Petterson", "Pettiti", "Petty", "Peytz", "Pfaltzgraff",
				"Philippe", "Philipsen", "Phillips", "Pialba", "Pierce",
				"Piil", "Pinholt", "PistoriusBecker", "Plambøck", "Plesner",
				"Podebusk", "Pontoppidan", "Poole", "Pope", "Pors", "Porteous",
				"Posse", "Posselt", "Poulsdatter", "Poulsen", "Povlsdatter",
				"Power", "Poznikoff", "Præstrud", "Praetorius", "Praff",
				"Prenger", "Prentice", "Price", "Primon", "Prins", "Prip",
				"Pritchard", "Prom", "Puggaard", "Purdon", "Pürschel",
				"Purwing", "Qualen", "Quist", "Quistgaard", "Qvist",
				"Qvistgaard", "Rabes", "Rabis", "Ræfdal", "Rager", "Rahnert",
				"Rais", "Ramos", "Ramsey", "Ramus", "Rani", "Rankin", "Rasch",
				"Rasmusdatter", "Rasmussen", "Rass", "Rauberg", "Rauch",
				"Ravn", "Ravnborg", "Ravnsgaard", "Reddersen", "Rediclffe",
				"Redsted", "Reedtz-Thott", "Reese", "Reffs", "Rehder",
				"Rehling", "Rehling-Quistgaard", "Rehling-Qvistgaard", "Reid",
				"Reimer", "Reimers", "Reimert", "Reinhard", "Reinhold",
				"Reinholdt", "Reinholdtsdatter", "Reinholtsdatter",
				"Reinmothtsen", "Reinsholm", "Renouard", "Resch", "Retsloff",
				"Reuter", "Reutze", "Reville", "Reymann", "Reyment",
				"Rheinlænder", "Ribeiro", "Ribers", "Ribolt", "Rice",
				"Richards", "Richardt", "Richie", "Rickerts", "Rieper", "Riis",
				"Riisbrigh", "Riise", "Rimboltsen", "Rindom", "Ring", "Risak",
				"Rischel", "Risøe", "Risom", "Risting", "Ritchie", "Ritmer",
				"Rix", "Rizer", "Roark", "Robbert", "Robbert-Rasmussen",
				"Robinson", "Rocho", "Rode", "Rødebæk", "Rodgers", "Roed",
				"Røen", "Rogers", "Roggenbau", "Rohde", "Røjkjær", "Rolley",
				"Rollin", "Rollwagen", "Roloff", "Rom", "Rømer", "Rommel",
				"Rønberg", "Rönchendorff", "Rønholdt", "Rønne", "Rookwood",
				"Rør", "Rørdam", "Rose", "Rosenberg", "Rosenbjerg",
				"Rosendahl", "Rosenkjær", "Rosenkrantz", "Rosenstand",
				"RosenstandGoiske", "Rosenthal", "Rosentoft", "Roslund",
				"Roslundh", "Rosman", "Rossau", "Rossov", "Rostgaard", "Rud",
				"Rüdinger", "Ruhwald", "Runge", "Rutten", "Ryan", 
				"Ryberg",
				"Rydberg", "Rygaard", "Ryge", "Ryving-Jensen", "Saabye",
				"Sabro", "Sabroe", "Sakariasen", "Salewsky", "Sally", "Salten",
				"Saltensee", "Salto", "Salvesen", "Sand", "Sandager",
				"Sandberg", "Sandbye", "Sande", "Sanders", "Sandersen",
				"Sandorff", "Sappi", "Sargent", "Saugmann", "Sauvaget",
				"Savage", "Saxby", "Scavenius", "Schack-Schou", "Schæffer",
				"Schæg", "Schäffer", "Schalburg", "Schaldemose", "Schanderup",
				"Schau", "Scheel", "Schelde", "Scheller", "Schepelern",
				"Schermer", "Schiemann", "Schiffer", "Schindberg", 
				"Schiödte",
				"Schiønning", "Schiøt", "Schjødt", "Schjørring", 
				"Schlegel",
				"Schlichter", "Schlorffers", "Schmedes", "Schmidt",
				"Schmidt-Nielsen", "Schmidt Qvist", "Schmith", "Schmitt",
				"Schmutter", "Schneekloth", "Schøller", "Schöps",
				"Schøpzinsky", "Schørling", "Schou", "Schouboe", "Schoupe",
				"Schousboe", "Schouw", "Schovgaard", "Schow", 
				"Schram",
				"Schrøder", "Schule", "Schultz", "Schumann", "Schwartz",
				"Schwartzkopf", "Schwarz", "Schytte", "Seelen", "Seerup",
				"Segelcke", "Sehard", "Seidel", "Seidelin", "Seidentopf",
				"Seiersäll", "Sejer", "Sejersen", "Sekker Hansen", "Seldon",
				"Selmer", "Sergeant", "Serlin", "Setter", "Severin", "Sexton",
				"Seymour", "Shah", "Sharp", "Sharry", "Shaw", "Sherrel",
				"Short", "Sidenius", "Siebert", "Sigaard", "Sigurdsdatter",
				"Sigvardsdatter", "Sigvardsen", "Sikker Hansen", "Silver",
				"Silwer", "Simmelhag", "Simonsdatter", "Simonsen", "Simpkins",
				"Simpson", "Sims", "Sindahl", "Sinnerup", "Sitapan",
				"Sjællandsfar", "Sjølander", "Sjörén", "Skagen", "Skavbo",
				"Skavlan", "Skelhøj", "Skibsted", "Skidenvad", "Skjalmsen",
				"Skjelmose", "Skjødt", "Skjoldager", "Skotte", "Skouboe",
				"Skov", "Skovdan", "Skoven", "Skovgaard", "Skovgård",
				"Skovhus", "Skrædder", "Skræder", "Skræders", "Skram",
				"Skriver", "Skydt", "Slamberg", "Slangerup", "Slanhoff",
				"Slee", "Sletved", "Sloth", "Smed", "Smidt", "Sminge", "Smith",
				"Smitt", "Smyth", "Snare", "Sneddon", "Sode", "Søe-Pedersen",
				"Søgaard", "Sohn", "Soldbro", "Sølling", "Sollohub", "Sols",
				"Solter", "Sommer", "Sønderbye", "Søndergaard", "Sønderup",
				"Sonne", "Sonnenberg", "Sonnenschmidt", "Sørensdatter",
				"Sørensen", "SørensenJørgensen", "Søvndahl-Petersen", "Spager",
				"Spangler", "Sparkes", "Sparre", "Spendt", "Sperling",
				"Spethmann", "Spiero", "Sprageleg", "Stæhr-Nielsen", "Stander",
				"Stanley", "Stanton", "Stapel", "Staphrophski", "Starkow",
				"Stchelkunoff", "Stech", "Steen", "Steenberg", "Steensen",
				"Steffansen", "Steffensdatter", "Steffensen", "Steiaholt",
				"Stellmacher", "Stenbeck", "Stenberg", "Stendrup",
				"Stenholm-Hansen", "Stensballe", "Stensson", "Stephens",
				"Stephensdatter", "Stephensen", "Sterck", "Stevens", "Stewart",
				"Stibe", "Stibolt", "Stilson", "Stobbe", "Stockfleth",
				"Stockmann", "Stockwell", "Stoier", "Stoklund",
				"Storbritannien og Irland", "Storch", "Storey", "Storm",
				"Storråde", "Støttrup", "Stougård", "Stough", "Stow", "Stowe",
				"Strand", "Strandberg", "Strandgaard", "Strange",
				"Strangesdatter", "Strate", "Stratmann", "Stricker",
				"Stroberg", "Strömer", "Strøm Petersen", "Stuve", "Stygge",
				"Suenson", "Suhr", "Sundström", "Sundt", "Sunesdatter",
				"Sunesen", "Sunke", "Sværdfegers", "Svane", "SvanenskjoldHoff",
				"Svarre", "Sveinbjörnsson", "Sveinbjørnsson", "Sveistrup",
				"Sven", "Svendborg", "Svendsdatter", "Svendsen", "Svensdatter",
				"Svensson", "Swanson", "Sweetnam", "Syberg", "Synderslev",
				"Szlenski", "Taarning", "Tack", "Talbot", "Tamm", "Tange",
				"Tapdrup", "Tarr", "Taul", "Taulov", "Teglbjærg", "Teilmann",
				"Telling", "Terchildsdatter", "Terchildsen", "Terkelsen",
				"Terkildsen", "Termansen", "Tetzen", "Thaarup", "Thalbitzer",
				"Thau", "Theil", "Theilgaard", "Theilmann", "Thejls", "Thelin",
				"Thelin-Rønholdt", "Themsen", "Themstrup", "Therkildsen",
				"Thestrup", "Thiesen", "Thirslund", "Thøgersdatter",
				"Thøgersen", "Thomas", "Thomasdatter", "Thomasen", "Thomassen",
				"Thomesen", "Thomessen", "Thomitsdatter", "Thompson",
				"Thomsen", "Thon", "Thor", "Thorbek", "Thorlacius", "Thorne",
				"Thorning", "Thorsager", "Thorsdatter", "Thorsen", "Thorup",
				"Thøstesen", "Thott", "Thoustrup", "Thrane", "Thrugilsøn",
				"Thuesdatter", "Thuresen", "Thustrup", "Thygesdatter",
				"Thygesen", "Tiedemann", "Tiedt", "Tjørnelund", "Todd", "Toft",
				"Toldby", "Tollefsen", "Tommerup", "Tønder-Lund", "Tønnesen",
				"Topp", "Tordsdatter", "Torfing", "Torkildsen", "Torn",
				"Tornøe", "Torp", "Tørresen", "Tørrisdatter", "Tørsleff",
				"Torstensen", "Town", "Traae", "Tracy", "Trahn", "Trampenberg",
				"Tranberg", "Trautner-Nielsen", "Treschow", "Trier", "Trige",
				"Trogelsen", "Trojel", "Trommeslager", "Truelsdatter",
				"Truelsen", "Tucker", "Türck", "Turner", "Tutein", "Tuxen",
				"Tvede", "Tyrwaldt", "U", "Udsen", "Udy", "Uf", "Uhler",
				"Uldum", "Ulfeldt", "Ulrich", "Unkersen", "Unnewehr", "Upshaw",
				"Uren", "Ursin", "Urup", "Ustri", "Vaa", "Vaillant", "Valbaum",
				"Valen", "Valentin", "Valentiner", "Valissant", "Vallis",
				"van Cernin", "Van Der Does", "van der Weel", "Vang", "Vannes",
				"van Podebusk", "Vatter", "Vaudra", "Vecchini",
				"Vedel-Petersen", "Vegge", "Veivers", "Vejnholt-Møller",
				"Vendelbo", "Vendelboe-Hersom", "Verdelin", "Verney",
				"Vesterberg", "Vestergaard", "Vett", "Viberg", "Viif",
				"Vilhelmsborg", "Vilhelmsen", "Villadsdatter", "Villaume",
				"Villaume Graff", "Viltoft", "Vincent", "Vinghoff", "Visborg",
				"Vladimirovich", "Vognsen", "Voigt", "Volckmann", "Voldfrom",
				"Vøldike", "Volf", "Volquartz", "von Ahlefeldt",
				"von Ahlefeldt-Laurvig", "von Baggesen", "von Bretsken",
				"von der Heide", "von Dresky", "von Dresky und Merzdorf",
				"von Dreyer", "von Fønss", "von Geldern", "von Gersdorff",
				"von Gerstenberg", "von Grafenried", "von Holm",
				"von Holstein", "von Holtermann", "von Ingensberg",
				"von Köstelin", "von Linstow", "von Lohse", "von Møinichen",
				"von Podebusk", "von Pohle", "von Prangen",
				"von Rehling-Quistgaard", "von Rehling-Qvistgaard",
				"von Reutern", "von Rhaden", "von Rosenschild",
				"von Schalburg", "von Schinkel", "von Seelen",
				"von Siemianowskaja", "von Staffeldt", "von Steinmann",
				"von Stricker", "von Thomsdorff", "von Wøldike", "von Würtzen",
				"Vosbein", "Voss", "Vrolsen", "Vuillaume", "Waagechristensen",
				"Wackerhausen", "Wade", "Wael", "Wager", "Wagner", "Wahlgren",
				"Waite", "Wales", "Walker", "Walter", "Wandal", "Wanscher",
				"Ward", "Wardinghuus", "Warmington", "Warner", "Watson",
				"Webb", "Weber", "Weedon", "Wefstsdatter", "Wefstsen",
				"Weichert", "Weidemann", "Weidichsen", "Weile", "Weiner",
				"Weis", "Wellhöfer", "Wells", "Wendel", "Wendell", "Wenström",
				"Wering", "Werner", "Werner-Larsen", "Wessel", "West",
				"Westengaard", "Westenholz", "Westergaard", "Westh", "Wexels",
				"White", "Wiarda", "Wiberg", "Wibkens", "Wienberg", "Wigelsen",
				"Wildfang", "Wilhelmi", "Wilhelmsdatter", "Wilhelmsen",
				"Wilian", "Wilkens", "Willaume", "Willaume-Fabricius",
				"Willaume-Jantzen", "Willemoes-Wissing", "William", "Williams",
				"Willmark", "Willumsdatter", "Willumsen", "Wind", "Windelin",
				"Windfeld", "Windfeld-Hansen", "Winding", "Wind-Jensen",
				"Winge", "Winsløw", "Winther", "Wisborg", "Wisbröker",
				"Wishar", "Wissmach", "Wistrøm", "Witt", "Witzke", "Wodstrup",
				"Woeldike", "Woldike", "Wöldike", "Wøldike", "Wolff",
				"Wolfrath", "Woller", "Woodward", "Worm", "Worsøe", "Wranér",
				"Wright", "Wulff", "Wulff-Jørgensen", "Würger", "Würtzen",
				"Wynn", "Yde", "Young", "Ziegler", "Zielian", "Ziliotto",
				"Zimmerli", "Zimmermann", "Žižka", "Zoffmann", 
				};

		String outputNavnF = "";

		Fonkod fonkod = new Fonkod("OFF");
		try {
			for (int i = 0; i < inputNavne.length; i++) {
				outputNavnF = fonkod.generateKey(inputNavne[i]);
				System.out.println(inputNavne[i] + "\t" + outputNavnF);
			}
		} catch (Exception e) {
			System.out.println("Fonkod exception: " + e.getMessage());
		}

	}
}
